name: CMake Windows

on: workflow_dispatch

jobs:
  cmake:
    runs-on: windows-latest
    steps:
      - name: Checkout Sirius repo
        uses: actions/checkout@v2
        with:
          repository: rte-france/sirius-solver
          path: ./sirius-solver
          ref: antares_integration
      - name: Configure Sirius
        working-directory: ./sirius-solver
        run: cmake -Ssrc -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=SiriusInstall -G "Visual Studio 16 2019"
      - name: Build & Install Sirius
        working-directory: ./sirius-solver
        run: cmake --build build/ --config Release --target INSTALL -- /maxcpucount
      - name: Upload sirius dll
        uses: actions/upload-artifact@v2
        with:
          name: sirius_solver.dll
          path: ./sirius-solver/SiriusInstall/bin/sirius_solver.dll
      - name: Add Sirius bin to path
        run: echo "${{ github.workspace }}\sirius-solver\SiriusInstall\bin" >> $GITHUB_PATH
      - name: dumpbintest
        run: |
          & "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/dumpbin.exe" /dependents "${{ github.workspace }}\sirius-solver\SiriusInstall\bin\sirius_solver.dll"
      - name: Checkout or-tools
        uses: actions/checkout@v2
        with:
          repository: jdarlay/or-tools
          path: ./or-tools
          ref: rte_dev_ls_unittest
      - name: Configure or-tools
        working-directory: ./or-tools
        run: cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 16 2019" -DBUILD_DEPS=ON -DUSE_SIRIUS=ON -Dsirius_solver_DIR="${{ github.workspace }}/sirius-solver/SiriusInstall/cmake" -DBUILD_TESTING=ON
      - name: Build tests
        working-directory: ./or-tools
        run: cmake --build build --config Release --target sirius_interface -- /maxcpucount
      - name: Upload libortools
        uses: actions/upload-artifact@v2
        with:
          name: libortools
          path: ./or-tools/build/RELEASE/bin/ortools.lib
      - name: Upload test
        uses: actions/upload-artifact@v2
        with:
          name: sirius_interface.exe
          path: ./or-tools/build/RELEASE/bin/sirius_interface.exe
      - name: dumpbin ./or-tools/build/RELEASE/bin/sirius_interface.exe
        run: |
          & "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/dumpbin.exe" /dependents "${{ github.workspace }}\or-tools\build\RELEASE\bin\sirius_interface.exe"
      - name: direct run
        run: .\or-tools\build\RELEASE\bin\sirius_interface.exe
      - name: Run interface tests
        working-directory: ./or-tools/build
        run: ctest -VV -C Release -R 'cxx_unittests_sirius_interface'