name: CMake Windows

on: workflow_dispatch

jobs:
  cmake:
    runs-on: windows-latest
    steps:
      - name: Setup python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Pip install reqs
        run: python3 -m pip install --user mypy-protobuf absl-py setuptools wheel numpy pandas virtualenv
      - name: Checkout Sirius repo
        uses: actions/checkout@v2
        with:
          repository: rte-france/sirius-solver
          path: ./sirius-solver
          ref: antares_integration
      - name: cmake help
        run: cmake --help
      - name: Configure Sirius
        working-directory: ./sirius-solver
        run: cmake -Ssrc -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=SiriusInstall -G "Visual Studio 16 2019"
      - name: Build & Install Sirius
        working-directory: ./sirius-solver
        run: cmake --build build/ --config Release --target INSTALL -- /maxcpucount
      - name: Upload sirius dll
        uses: actions/upload-artifact@v2
        with:
          name: sirius_solver
          path: ./sirius-solver/SiriusInstall/bin/sirius_solver.dll
      - name: Add Sirius bin to path
        shell: bash
        run: echo "${{ github.workspace }}\sirius-solver\SiriusInstall\bin" >> $GITHUB_PATH
      - name: Checkout xpressmp813Win
        uses: actions/checkout@v2
        with:
          repository: jdarlay/xpressmp813Win
          path: ./xpressmp813
          ref: master
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Add xpress bin to path
        shell: bash
        run: echo "${{ github.workspace }}\xpressmp813\bin" >> $GITHUB_PATH
      - name: Checkout or-tools
        uses: actions/checkout@v2
        with:
          repository: jdarlay/or-tools
          path: ./or-tools
          ref: rte_dev_ls_cmake_windows_python
      - name: Configure or-tools
        working-directory: ./or-tools
        run: cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 16 2019" -DBUILD_DEPS=ON -DUSE_SIRIUS=ON -Dsirius_solver_DIR="${{ github.workspace }}/sirius-solver/SiriusInstall/cmake" -DUSE_XPRESS=ON -DXPRESS_ROOT="${{ github.workspace }}/xpressmp813" -DBUILD_PYTHON=ON
      - name: Build tests
        working-directory: ./or-tools
        run: cmake --build build --config Release --target sirius_interface xpress_interface python_package -v -- /maxcpucount
      - name: Upload libortools
        uses: actions/upload-artifact@v2
        with:
          name: libortools
          path: ./or-tools/build/RELEASE/bin/ortools.lib
      - name: Run interface tests
        working-directory: ./or-tools/build
        run: ctest -V -C Release -R 'cxx_unittests_*'
      - name: Run python tests
        working-directory: ./or-tools/build
        run: ctest -V -R python_python_linear_programming_sirius_xpress
