name: CMake artifact

on: workflow_dispatch

jobs:
  cmake:
    runs-on: windows-latest
    steps:
      - name: Checkout sirius_action
        uses: actions/checkout@v2
      - name: Upload ortools dotnet
        uses: actions/upload-artifact@v2
        with:
          name: ortools_dotnet
          path: |
            ./artifact_test/Google.OrTools.[0-9]*.[0-9]*.[0-9]*.nupkg
            ./artifact_test/Google.OrTools.runtime.*.[0-9]*.[0-9]*.[0-9]*.nupkg
