name: Install Sirius

on: workflow_dispatch

jobs:
  cmake:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Sirius repo
        uses: actions/checkout@v2
        with:
          repository: rte-france/sirius-solver
          path: ./sirius-solver
          ref: master
      - name: Configure Sirius
        working-directory: ./sirius-solver
        run: |
          cmake -S src \
                -B build \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX=SiriusInstall
      - name: Build & Install Sirius
        working-directory: ./sirius-solver
        run: cmake --build build/ --config Release --target install -j14
      - name: Tree
        working-directory: ./sirius-solver/SiriusInstall
        run: tree . && exit 1
      - name: Checkout or-tools
        uses: actions/checkout@v2
        with:
          repository: jdarlay/or-tools
          path: ./or-tools
          ref: rte_dev_ls_unittest
      - name: Configure or-tools
        working-directory: ./or-tools
        shell: bash
        run: |
          cmake -S. \
                -Bbuild \
                -DCMAKE_BUILD_TYPE=Release \
                -DBUILD_DEPS=ON \
                -DUSE_SIRIUS=ON \
                -Dsirius_solver_DIR="${{ github.workspace }}/sirius-solver/SiriusInstall/cmake" \
                -DBUILD_LINEAR_SOLVER_UNITTESTS=ON \
                -DBUILD_TESTING=ON
      - name: Build tests
        working-directory: ./or-tools
        run: |
          cmake --build build \
                --targets sirius_interface \
                -j14
      - name: Run tests
        working-directory: ./or-tools/build
        run: ctest -V -R 'cxx_unittests_.*'
