name: Install Sirius

on: workflow_dispatch

jobs:
  cmake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sirius repo
        uses: actions/checkout@v2
        with:
          repository: rte-france/sirius-solver
          path: ./sirius-solver
          ref: master
      - name: Configure Sirius
        working-directory: ./sirius-solver
        run: cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=SiriusInstall -B build -S src
      - name: Build & Install Sirius
        working-directory: ./sirius-solver
        run: cmake -j14 --build build/ --config Release --target install
      - name: Checkout or-tools
        uses: actions/checkout@v2
        with:
          repository: jdarlay/or-tools
          path: ./or-tools
          ref: rte_dev_ls_unittest
      - name: Configure or-tools
        working-directory: ./or-tools
        shell: bash
        run: cmake -j14 -S. -Bbuild -DCMAKE_BUILD_TYPE=Release -DBUILD_DEPS=ON -DUSE_SIRIUS=ON -Dsirius_solver_DIR=$(realpath ../sirius-solver/SiriusInstall)